<?php
/**
 * @author Koroph <yjk@outlook.fr | yjkof1596@gmail.com>
 *
 * @website http://koroph.site
 * @link  https://github.com/Koroph
 * @license MIT
 * @copyright Copyright (c) 2020.
 */


namespace KH\Browser\Kit;


class BrowserLanguage
{

    /**
     * @return Lang
     */
    public static function Primary(): Lang
    {
        $_lang = self::getBrowserLangCode();
        $_countryCode = self::getUserCountryCode();

        return new Lang($_lang, self::langAccept($_lang), "1.0", $_countryCode, self::countryAccept($_countryCode));
    }

    /**
     * @return array
     */
    public function LanguageRaw(): array
    {
        return self::dataRaw();
    }

    /**
     * @return array
     */
    private static function dataRaw(): array
    {
        return explode(';', $_SERVER['HTTP_ACCEPT_LANGUAGE']);
    }

    private static function getBrowserLangCode(): string
    {
        return substr(self::dataRaw()[0], -2) ?? 'fr';
    }

    private static function getUserCountryCode(): string
    {
        return strtolower(substr(self::dataRaw()[0], 3, 2) ?? "OO");
    }

    private static function langAccept(string $key): string
    {
        return [
                "fr" => "Français",
                "en" => "Anglais",
                "es" => "Espagnol",
                "de" => "allemand",
                "bg" => "bulgare",
                "cs" => "tchèque",
                "da" => "danois",
                "et" => "estonien",
                "el" => "grec",
                "ga" => "irlandais",
                "hr" => "croate",
                "it" => "italien",
                "lv" => "letton",
                "lt" => "lituanien",
                "hu" => "hongrois",
                "mt" => "maltais",
                "nl" => "néerlandais",
                "pl" => "polonais",
                "pt" => "portugais",
                "ro" => "roumain",
                "sk" => "slovaque",
                "sl" => "slovène",
                "sv" => "suédois",
                "fi" => "finnois",
            ][$key] ?? 'not defined';
    }

    private static function countryAccept(string $key): string
    {
        return [
                "ci" => "Cote d'ivoire",
                "fr" => "France",
                "ch" => "Suisse",
                "za" => "Afrique du Sud",
                "zm" => "Zambie",
                "zw" => "Zimbabwe",
                "dm" => "Dominique",
                "do" => "République dominicaine",
                "dz" => "Algérie",
                "ec" => "Equateur",
                "ee" => "Estonie",
                "eg" => "Egypte",
                "eh" => "Sahara occidental",
                "er" => "Érythrée",
                "es" => "Espagne",
                "et" => "Ethiopie",
                "fi" => "Finlande",
                "fj" => "Fidji",
                "fk" => "les îles Falkland",
                "fm" => "États fédérés de Micronésie",
                "fo" => "Îles Féroé",
                "ad" => "Andorre",
                "ae" => "Emirats Arabes Unis",
                "af" => "Afghanistan",
                "ag" => "Antigua-et-Barbuda",
                "ai" => "Anguilla",
                "al" => "Albanie",
                "am" => "Arménie",
                "an" => "Antilles néerlandaises",
                "ao" => "Angola",
                "aq" => "Antarctique",
                "ar" => "Argentine",
                "as" => "Samoa américaines",
                "at" => "Autriche",
                "au" => "Australie",
                "aw" => "Aruba",
                "ax" => "Aland Islands",
                "az" => "Azerbaijan",
                "ba" => "Bosnie Herzégovine",
                "bb" => "Barbados",
                "bd" => "Bangladesh",
                "be" => "Belgique",
                "bf" => "Burkina Faso",
                "bg" => "Bulgarie",
                "bh" => "Bahreïn",
                "bi" => "Burundi",
                "bj" => "Benin",
                "bm" => "Bermuda",
                "bn" => "Brunei Darussalam",
                "bo" => "Bolivia",
                "br" => "Brazil",
                "bs" => "Bahamas",
                "bt" => "Bhutan",
                "bv" => "Bouvet Island",
                "bw" => "Botswana",
                "by" => "Belarus",
                "bz" => "Belize",
                "ca" => "Canada",
                "cb" => "Nations des Caraïbes",
                "cc" => "Cocos(Keeling) Islands",
                "cd" => "République Démocratique du Congo",
                "cf" => "République centrafricaine",
                "cg" => "Congo",
                "ck" => "Cook Islands",
                "cl" => "Chili",
                "cm" => "Cameroon",
                "cn" => "Chine",
                "co" => "Colombie",
                "cr" => "Costa Rica",
                "cs" => "Serbie et Monténégro",
                "cu" => "Cuba",
                "cv" => "Cape Verde",
                "cx" => "L'île de noël",
                "cy" => "Cyprus",
                "cz" => "République Tchèque",
                "de" => "Allemagne",
                "dj" => "Djibouti",
                "dk" => "Denmark",
                "fx" => "France, métropolitaine",
                "ga" => "Gabon",
                "gb" => "Royaume-Uni",
                "gd" => "Grenada",
                "ge" => "Géorgie",
                "gf" => "Guyane Française",
                "gh" => "Ghana",
                "gi" => "Gibraltar",
                "gl" => "Greenland",
                "gm" => "Gambie",
                "gn" => "Guinée",
                "gp" => "Guadeloupe",
                "gq" => "Guinée Équatoriale",
                "gr" => "Greece",
                "gs" => "S . Georgia and S . Sandwich Islands",
                "gt" => "Guatemala",
                "gu" => "Guam",
                "gw" => "Guinée - Bissau",
                "gy" => "Guyana",
                "hk" => "Hong Kong",
                "hm" => "Heard Island and McDonald Islands",
                "hn" => "Honduras",
                "hr" => "Croatia",
                "ht" => "Haïti",
                "hu" => "Hongrie",
                "id" => "Indonésie",
                "ie" => "Irlande",
                "il" => "Israel",
                "in" => "India",
                "io" => "Territoire britannique de l'océan Indien",
                "iq" => "Irak",
                "ir" => "Iran",
                "is" => "Islande",
                "it" => "Italie",
                "jm" => "Jamaïque",
                "jo" => "Jordan",
                "jp" => "Japon",
                "ke" => "Kenya",
                "kg" => "Kirghizistan",
                "kh" => "Cambodge",
                "ki" => "Kiribati",
                "km" => "Comores",
                "kn" => "Saint Kitts and Nevis",
                "kp" => "Corée (Nord)",
                "kr" => "Corée",
                "kw" => "Koweit",
                "ky" => "Îles Caïmans",
                "kz" => "Kazakhstan",
                "la" => "Laos",
                "lb" => "Liban",
                "lc" => "Sainte-Lucie",
                "li" => "Liechtenstein",
                "lk" => "Sri Lanka",
                "lr" => "Liberia",
                "ls" => "Lesotho",
                "lt" => "Lituanie",
                "lu" => "Luxembourg",
                "lv" => "Lettonie",
                "ly" => "Libye",
                "ma" => "Maroc",
                "mc" => "Monaco",
                "md" => "Moldavie",
                "mg" => "Madagascar",
                "mh" => "Iles Marshall",
                "mk" => "Macédoine",
                "ml" => "Mali",
                "mm" => "Myanmar",
                "mn" => "Mongolie",
                "mo" => "Macao",
                "mp" => "Îles Mariannes du Nord",
                "mq" => "Martinique",
                "mr" => "Mauritanie",
                "ms" => "Montserrat",
                "mt" => "Malta",
                "mu" => "Mauritius",
                "mv" => "Maldives",
                "mw" => "Malawi",
                "mx" => "Mexique",
                "my" => "Malaisie",
                "mz" => "Mozambique",
                "na" => "Namibie",
                "nc" => "Nouvelle Calédonie",
                "ne" => "Niger",
                "nf" => "Norfolk Island",
                "ng" => "Nigeria",
                "ni" => "Nicaragua",
                "nl" => "Pays-Bas",
                "no" => "Norvège",
                "np" => "Népal",
                "nr" => "Nauru",
                "nu" => "Niue",
                "nz" => "Nouvelle-Zélande",
                "om" => "Sultanat d'Oman",
                "oo" => "Autre",
                "pa" => "Panama",
                "pe" => "Pérou",
                "pf" => "Polynésie française",
                "pg" => "Papouasie Nouvelle Guinée",
                "ph" => "Philippines",
                "pk" => "Pakistan",
                "pl" => "Pologne",
                "pm" => "Saint-Pierre-et-Miquelon",
                "pn" => "Pitcairn",
                "pr" => "Porto Rico",
                "ps" => "Territoire Palestinien",
                "pt" => "Portugal",
                "pw" => "Palau",
                "py" => "Paraguay",
                "qa" => "Qatar",
                "re" => "Réunion",
                "ro" => "Roumanie",
                "ru" => "Fédération Russe",
                "rw" => "Rwanda",
                "sa" => "Arabie Saoudite",
                "sb" => "Les îles Salomon",
                "sc" => "Seychelles",
                "sd" => "Soudan",
                "se" => "Suède",
                "sg" => "Singapore",
                "sh" => "Sainte-Hélène",
                "si" => "Slovénie",
                "sj" => "Svalbard and Jan Mayen",
                "sk" => "République slovaque",
                "sl" => "Sierra Leone",
                "sm" => "Saint Marin",
                "sn" => "Senegal",
                "so" => "Somalie",
                "sr" => "Suriname",
                "st" => "Sao Tome and Principe",
                "sv" => "Le Salvador",
                "sy" => "Syrie",
                "sz" => "Swaziland",
                "tc" => "îles Turques-et-Caïques",
                "td" => "Tchad",
                "tf" => "Terres australes françaises",
                "tg" => "Togo",
                "th" => "Thailand",
                "tj" => "Tajikistan",
                "tk" => "Tokelau",
                "tl" => "Timor - Leste",
                "tm" => "Turkménistan",
                "tn" => "Tunisie",
                "to" => "Tonga",
                "tp" => "Timor oriental",
                "tr" => "dinde",
                "tt" => "Trinité-et-Tobago",
                "tv" => "Tuvalu",
                "tw" => "Taiwan",
                "tz" => "Tanzanie",
                "ua" => "Ukraine",
                "ug" => "Ouganda",
                "us" => "États-Unis",
                "uy" => "Uruguay",
                "uz" => "Uzbekistan",
                "va" => "État de la Cité du Vatican",
                "vc" => "Saint-Vincent-et-les-Grenadines",
                "ve" => "Venezuela",
                "vg" => "Virgin Islands(British)",
                "vi" => "Virgin Islands(U.S)",
                "vn" => "Vietnam",
                "vu" => "Vanuatu",
                "wf" => "Wallis and Futuna",
                "ws" => "Samoa",
                "ye" => "Yemen",
                "yt" => "Mayotte",
                "yu" => "Yougoslavie",
            ][$key] ?? 'not defined';
    }
}
/*private static function countryAccept(): array
{
    return [
        "ci" => "Cote d'ivoire",
        "fr" => "France",
        "ch" => "Suisse",
        "za" => "South Africa",
        "zm" => "Zambie",
        "zw" => "Zimbabwe",
        "dm" => "Dominica",
        "do" => "Dominican Republic",
        "dz" => "Algeria",
        "ec" => "Ecuador",
        "ee" => "Estonia",
        "eg" => "Egypt",
        "eh" => "Western Sahara",
        "er" => "Eritrea",
        "es" => "Spain",
        "et" => "Ethiopia",
        "fi" => "Finland",
        "fj" => "Fiji",
        "fk" => "Falkland Islands(Malvinas)",
        "fm" => "Federated States of Micronesia",
        "fo" => "Faroe Islands",
        "ad" => "Andorra",
        "ae" => "United Arab Emirates",
        "af" => "Afghanistan",
        "ag" => "Antigua and Barbuda",
        "ai" => "Anguilla",
        "al" => "Albania",
        "am" => "Armenia",
        "an" => "Netherlands Antilles",
        "ao" => "Angola",
        "aq" => "Antarctica",
        "ar" => "Argentina",
        "as" => "American Samoa",
        "at" => "Austria",
        "au" => "Australia",
        "aw" => "Aruba",
        "ax" => "Aland Islands",
        "az" => "Azerbaijan",
        "ba" => "Bosnia and Herzegovina",
        "bb" => "Barbados",
        "bd" => "Bangladesh",
        "be" => "Belgium",
        "bf" => "Burkina Faso",
        "bg" => "Bulgaria",
        "bh" => "Bahrain",
        "bi" => "Burundi",
        "bj" => "Benin",
        "bm" => "Bermuda",
        "bn" => "Brunei Darussalam",
        "bo" => "Bolivia",
        "br" => "Brazil",
        "bs" => "Bahamas",
        "bt" => "Bhutan",
        "bv" => "Bouvet Island",
        "bw" => "Botswana",
        "by" => "Belarus",
        "bz" => "Belize",
        "ca" => "Canada",
        "cb" => "Caribbean Nations",
        "cc" => "Cocos(Keeling) Islands",
        "cd" => "Democratic Republic of the Congo",
        "cf" => "Central African Republic",
        "cg" => "Congo",
        "ck" => "Cook Islands",
        "cl" => "Chile",
        "cm" => "Cameroon",
        "cn" => "China",
        "co" => "Colombia",
        "cr" => "Costa Rica",
        "cs" => "Serbia and Montenegro",
        "cu" => "Cuba",
        "cv" => "Cape Verde",
        "cx" => "Christmas Island",
        "cy" => "Cyprus",
        "cz" => "Czech Republic",
        "de" => "Germany",
        "dj" => "Djibouti",
        "dk" => "Denmark",
        "fx" => "France, Metropolitan",
        "ga" => "Gabon",
        "gb" => "United Kingdom",
        "gd" => "Grenada",
        "ge" => "Georgia",
        "gf" => "French Guiana",
        "gh" => "Ghana",
        "gi" => "Gibraltar",
        "gl" => "Greenland",
        "gm" => "Gambia",
        "gn" => "Guinea",
        "gp" => "Guadeloupe",
        "gq" => "Equatorial Guinea",
        "gr" => "Greece",
        "gs" => "S . Georgia and S . Sandwich Islands",
        "gt" => "Guatemala",
        "gu" => "Guam",
        "gw" => "Guinea - Bissau",
        "gy" => "Guyana",
        "hk" => "Hong Kong",
        "hm" => "Heard Island and McDonald Islands",
        "hn" => "Honduras",
        "hr" => "Croatia",
        "ht" => "Haiti",
        "hu" => "Hungary",
        "id" => "Indonesia",
        "ie" => "Ireland",
        "il" => "Israel",
        "in" => "India",
        "io" => "British Indian Ocean Territory",
        "iq" => "Iraq",
        "ir" => "Iran",
        "is" => "Iceland",
        "it" => "Italy",
        "jm" => "Jamaica",
        "jo" => "Jordan",
        "jp" => "Japan",
        "ke" => "Kenya",
        "kg" => "Kyrgyzstan",
        "kh" => "Cambodia",
        "ki" => "Kiribati",
        "km" => "Comoros",
        "kn" => "Saint Kitts and Nevis",
        "kp" => "Korea(North)",
        "kr" => "Korea",
        "kw" => "Kuwait",
        "ky" => "Cayman Islands",
        "kz" => "Kazakhstan",
        "la" => "Laos",
        "lb" => "Lebanon",
        "lc" => "Saint Lucia",
        "li" => "Liechtenstein",
        "lk" => "Sri Lanka",
        "lr" => "Liberia",
        "ls" => "Lesotho",
        "lt" => "Lithuania",
        "lu" => "Luxembourg",
        "lv" => "Latvia",
        "ly" => "Libya",
        "ma" => "Morocco",
        "mc" => "Monaco",
        "md" => "Moldova",
        "mg" => "Madagascar",
        "mh" => "Marshall Islands",
        "mk" => "Macedonia",
        "ml" => "Mali",
        "mm" => "Myanmar",
        "mn" => "Mongolia",
        "mo" => "Macao",
        "mp" => "Northern Mariana Islands",
        "mq" => "Martinique",
        "mr" => "Mauritania",
        "ms" => "Montserrat",
        "mt" => "Malta",
        "mu" => "Mauritius",
        "mv" => "Maldives",
        "mw" => "Malawi",
        "mx" => "Mexico",
        "my" => "Malaysia",
        "mz" => "Mozambique",
        "na" => "Namibia",
        "nc" => "new Caledonia",
        "ne" => "Niger",
        "nf" => "Norfolk Island",
        "ng" => "Nigeria",
        "ni" => "Nicaragua",
        "nl" => "Netherlands",
        "no" => "Norway",
        "np" => "Nepal",
        "nr" => "Nauru",
        "nu" => "Niue",
        "nz" => "new Zealand",
        "om" => "Sultanate of Oman",
        "oo" => "Other",
        "pa" => "Panama",
        "pe" => "Peru",
        "pf" => "French Polynesia",
        "pg" => "Papua new Guinea",
        "ph" => "Philippines",
        "pk" => "Pakistan",
        "pl" => "Poland",
        "pm" => "Saint Pierre and Miquelon",
        "pn" => "Pitcairn",
        "pr" => "Puerto Rico",
        "ps" => "Palestinian Territory",
        "pt" => "Portugal",
        "pw" => "Palau",
        "py" => "Paraguay",
        "qa" => "Qatar",
        "re" => "Reunion",
        "ro" => "Romania",
        "ru" => "Russian Federation",
        "rw" => "Rwanda",
        "sa" => "Saudi Arabia",
        "sb" => "Solomon Islands",
        "sc" => "Seychelles",
        "sd" => "Sudan",
        "se" => "Sweden",
        "sg" => "Singapore",
        "sh" => "Saint Helena",
        "si" => "Slovenia",
        "sj" => "Svalbard and Jan Mayen",
        "sk" => "Slovak Republic",
        "sl" => "Sierra Leone",
        "sm" => "San Marino",
        "sn" => "Senegal",
        "so" => "Somalia",
        "sr" => "Suriname",
        "st" => "Sao Tome and Principe",
        "sv" => "El Salvador",
        "sy" => "Syria",
        "sz" => "Swaziland",
        "tc" => "Turks and Caicos Islands",
        "td" => "Chad",
        "tf" => "French Southern Territories",
        "tg" => "Togo",
        "th" => "Thailand",
        "tj" => "Tajikistan",
        "tk" => "Tokelau",
        "tl" => "Timor - Leste",
        "tm" => "Turkmenistan",
        "tn" => "Tunisia",
        "to" => "Tonga",
        "tp" => "East Timor",
        "tr" => "Turkey",
        "tt" => "Trinidad and Tobago",
        "tv" => "Tuvalu",
        "tw" => "Taiwan",
        "tz" => "Tanzania",
        "ua" => "Ukraine",
        "ug" => "Uganda",
        "us" => "United States",
        "uy" => "Uruguay",
        "uz" => "Uzbekistan",
        "va" => "Vatican City State(Holy See)",
        "vc" => "Saint Vincent and the Grenadines",
        "ve" => "Venezuela",
        "vg" => "Virgin Islands(British)",
        "vi" => "Virgin Islands(U . S .)",
        "vn" => "Vietnam",
        "vu" => "Vanuatu",
        "wf" => "Wallis and Futuna",
        "ws" => "Samoa",
        "ye" => "Yemen",
        "yt" => "Mayotte",
        "yu" => "Yugoslavia",
    ];
}*/



